/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-12-24 07:54:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.freeBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class freeBoardMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#searchBtn\").on(\"click\", function(){\r\n");
      out.write("\t\t\tvar regExIsNumeric = /^[0-9]+$/;\r\n");
      out.write("\t\t\tvar deleteBlank = / /gi;\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar searchSelect = $(\"#searchSelect\").val();\r\n");
      out.write("\t\t\tvar searchKeyword = $(\"#searchKeyword\").val().replace(deleteBlank, \"\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tif(searchSelect == 'num' && !searchKeyword.replace(regExIsNumeric, \"\") == \"\"){\r\n");
      out.write("\t\t\t\talert(\"검색어를 확인해주세요.\\n글번호 검색은 숫자만 가능합니다.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar searchJson = {searchField: searchSelect, keyword: searchKeyword};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.log(searchJson);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\tdata: searchJson,\r\n");
      out.write("\t\t\t\tcontentType: 'application/json;charset=UTF-8',\r\n");
      out.write("\t\t\t\turl: \"./mainSearch.ino\",\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t$(\"#boardTable\").empty();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar tbody = $(\"<tbody></tbody>\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data.length > 0){\r\n");
      out.write("\t\t\t\t\t\t$.each(data, function(idx, board){\r\n");
      out.write("\t\t\t\t\t\t\tvar tr = $(\"<tr></tr>\");\r\n");
      out.write("\t\t\t\t\t\t\tvar type = $(\"<td style='width: 55px; padding-left: 30px;' align='center'></td>\").html(board.codeType);\r\n");
      out.write("\t\t\t\t\t\t\tvar num = $(\"<td style='width: 50px; padding-left: 10px;' align='center'></td>\").html(board.num);\r\n");
      out.write("\t\t\t\t\t\t\tvar link = $(\"<a href='./freeBoardDetail.ino?num=\"+board.num+\"'></a>\");\r\n");
      out.write("\t\t\t\t\t\t\tvar title = $(\"<td style='width: 125px;' align='center'></td>\").text(board.title);\r\n");
      out.write("\t\t\t\t\t\t\tlink.append(title);\r\n");
      out.write("\t\t\t\t\t\t\tvar name = $(\"<td style='width: 48px; padding-left: 50px;' align='center'></td>\").html(board.name);\r\n");
      out.write("\t\t\t\t\t\t\tvar regdate = $(\"<td style='width: 100px; padding-left: 95px;' align='center'></td>\").html(board.regdate);\r\n");
      out.write("\t\t\t\t\t\t\ttr.append(type, num, link, name, regdate);\r\n");
      out.write("\t\t\t\t\t\t\ttbody.append(tr);\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tvar h4 = $(\"<h4 style='padding: 20px'></h4>\").html(\"검색어에 해당하는 결과가 존재하지 않습니다.\");\r\n");
      out.write("\t\t\t\t\t\tvar button = $(\"<button>목록으로</button>\").attr(\"onClick\", \"location.href='./main.ino'\");\r\n");
      out.write("\t\t\t\t\t\ttbody.append(h4, button);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#boardTable\").append(tbody);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(request, status, error){\r\n");
      out.write("\t\t\t\t\tconsole.log(status);\r\n");
      out.write("\t\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h1>자유게시판</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<select id=\"searchSelect\">\r\n");
      out.write("\t\t\t<option value=\"num\">글번호</option>\r\n");
      out.write("\t\t\t<option value=\"title\">글제목</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<input type=\"text\" id=\"searchKeyword\"/>\r\n");
      out.write("\t\t<button type=\"button\" id=\"searchBtn\" name=\"searchBtn\">검색</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"width:650px;\" align=\"right\">\r\n");
      out.write("\t\t<a href=\"./freeBoardInsert.ino\">글쓰기</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr style=\"width: 600px;\">\r\n");
      out.write("\t<div style=\"padding-bottom: 10px;\">\r\n");
      out.write("\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 55px; padding-left: 30px;\" align=\"center\">타입</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 50px; padding-left: 10px;\" align=\"center\">글번호</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 125px;\" align=\"center\">글제목</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 48px; padding-left: 50px;\" align=\"center\">글쓴이</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 100px; padding-left: 95px;\" align=\"center\">작성일시</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr style=\"width: 600px;\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"boardDiv\">\r\n");
      out.write("\t\t<table id=\"boardTable\" border=\"1\">\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/view/freeBoard/freeBoardMain.jsp(104,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("dto");
    // /WEB-INF/view/freeBoard/freeBoardMain.jsp(104,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/freeBoard/freeBoardMain.jsp(104,5) '${ freeBoardList }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${ freeBoardList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t<td style=\"width: 55px; padding-left: 30px;\" align=\"center\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ dto.codeType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t<td style=\"width: 50px; padding-left: 10px;\" align=\"center\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ dto.num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t<td style=\"width: 125px; align=\"center\"><a href=\"./freeBoardDetail.ino?num=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ dto.num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ dto.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a></td>\r\n");
          out.write("\t\t\t\t\t\t<td style=\"width: 48px; padding-left: 50px;\" align=\"center\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ dto.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t<td style=\"width: 100px; padding-left: 95px;\" align=\"center\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ dto.regdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
